# this is a yaml anchor where multiple service can reference the same base
# the "x-" is a convertion for extension fields which is ignored by docker
x-backend-base: &backend-base
  build:
    context: ./backend/
    dockerfile: Dockerfile
  restart: always
  env_file:
    - ./backend/.env
  ports:
    - "8080:8080"
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy

x-frontend-base: &frontend-base
  build:
    context: ./frontend/
    dockerfile: Dockerfile
  restart: always

services:
  # -------------------------------------------------------------------------------------
  # DEVLOPMENT
  # -------------------------------------------------------------------------------------

  dev-frontend:
    <<: *frontend-base
    profiles: ["dev"]
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: development
    ports:
      - "80:80"
    volumes:
      - ./frontend/:/app
      - /app/node_modules

  dev-backend:
    <<: *backend-base
    profiles: ["dev"] # this tell docker compose what services to build
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: development # this is targeting the backend dockerfile development
    restart: always
    environment:
      - GIN_MODE=debug
    volumes:
      - ./backend/:/app
      - /app/tmp
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./backend
    #       target: /app
    #       ignore:
    #         - tmp/
    #         - vendor/
    #     - action: rebuild
    #       path: ./backend/go.mod
    #     - action: rebuild
    #       path: ./backend/go.sum

  # -------------------------------------------------------------------------------------
  # PRODUCTION
  # -------------------------------------------------------------------------------------
  production-backend:
    <<: *backend-base
    profiles: ["prod"]
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: production
    environment:
      - GIN_MODE=release

  production-frontend:
    <<: *frontend-base
    profiles: ["prod"]
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: production

  #this service name acts as the host name db connection
  postgres:
    profiles: ["dev", "prod"]
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-urlshortener}
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres-password}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migration:/docker-entrypoint-initdb.d

  redis:
    profiles: ["dev", "prod"]
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispassword}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $${REDIS_PASSWORD} ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

# ----------------------------------------------------------------------------------------
